services:
    cache_time_keeper.driver.dummy:
        class: AnimeDb\Bundle\CacheTimeKeeperBundle\Service\Driver\Dummy
        public: false

    cache_time_keeper.driver.file:
        class: AnimeDb\Bundle\CacheTimeKeeperBundle\Service\Driver\File
        arguments: [ '%cache_time_keeper.driver.file.path%' ]
        public: false

    cache_time_keeper.driver.shmop:
        class: AnimeDb\Bundle\CacheTimeKeeperBundle\Service\Driver\Shmop
        arguments: [ '%cache_time_keeper.driver.shmop.salt%' ]
        public: false

    cache_time_keeper.driver.multi:
        class: AnimeDb\Bundle\CacheTimeKeeperBundle\Service\Driver\Multi
        arguments: [ '@cache_time_keeper.driver.multi.fast', '@cache_time_keeper.driver.multi.slow' ]
        public: false

    cache_time_keeper.driver.memcache:
        class: AnimeDb\Bundle\CacheTimeKeeperBundle\Service\Driver\Memcache
        arguments: [ '@cache_time_keeper.memcache', '%cache_time_keeper.driver.memcache.prefix%' ]
        public: false

    cache_time_keeper.memcache:
        class: Memcache
        public: false
