services:
    cache_time_keeper.listener.entity:
        class: AnimeDb\Bundle\CacheTimeKeeperBundle\Event\Listener\DoctrineListener
        arguments: [ '@cache_time_keeper', '%cache_time_keeper.track.individually_entity%' ]
        tags:
            - { name: doctrine.event_listener, event: postRemove }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }

    cache_time_keeper.listener.console:
        class: AnimeDb\Bundle\CacheTimeKeeperBundle\Event\Listener\ConsoleListener
        arguments: [ '@cache_time_keeper', ~ ]
        tags:
            - { name: kernel.event_listener, event: console.terminate, method: onTerminate }

    cache_time_keeper.listener.exception:
        class: AnimeDb\Bundle\CacheTimeKeeperBundle\Event\Listener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
