language: php

sudo: false

php:
    - 5.5
    - 5.6
    - 7.0

notifications:
    email: dev@anime-db.org

before_install:
    - echo "extension=memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer self-update
    - 'if [[ -n "$GH_TOKEN" ]]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;'
    - mkdir build

install:
    - composer install --prefer-dist --no-interaction --no-progress

script:
    - vendor/bin/phpunit

after_script:
    - vendor/bin/ocular code-coverage:upload --format=php-clover build/coverage-clover.xml
    - vendor/bin/coveralls -v -c .coveralls.yml
