language: php

sudo: false

php:
    #- 7.1 # build failed #24
    - 7.0
    - 5.6
    - 5.5
    - hhvm

notifications:
    email: dev@anime-db.org

matrix:
    fast_finish: true
    include:
        - php: 5.6
          env: COVERAGE=1
        - php: 5.6
          env: SYMFONY_VERSION=2.3.*
        - php: 5.6
          env: SYMFONY_VERSION=2.7.*
        - php: 5.6
          env: SYMFONY_VERSION=2.8.*
        - php: 5.6
          env: SYMFONY_VERSION=3.0.*
    allow_failures:
        - php: hhvm

before_install:
    - if [ "$TRAVIS_PHP_VERSION" == "5.5" ] || [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then echo "extension=memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$COVERAGE" != "1" ]; then phpenv config-rm xdebug.ini; fi;
    - composer self-update
    - mkdir build

install:
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --dev --no-update; fi;
    - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then composer remove "anime-db/shmop" --dev --no-update; fi;
    - composer install --prefer-dist --no-interaction --no-progress

script:
    - if [ "$COVERAGE" != "1" ]; then vendor/bin/phpunit; fi;
    - if [ "$COVERAGE" == "1" ]; then vendor/bin/phpunit --coverage-clover build/coverage-clover.xml; fi;

after_script:
    - if [ "$COVERAGE" == "1" ]; then vendor/bin/ocular code-coverage:upload --format=php-clover build/coverage-clover.xml; fi;
    - if [ "$COVERAGE" == "1" ]; then vendor/bin/coveralls -v -c .coveralls.yml; fi;
