language: php

php:
    - 5.5
    - 5.6
    - 7.0

services:
    - memcached

notifications:
    email: dev@anime-db.org

install:
    - pecl install -f memcache
    - echo "extension=memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer self-update
    - composer install --prefer-source

script:
    - phpunit --verbose --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
