language: php

sudo: false

php:
    #- 7.1 # build failed #24
    - 7.0
    - 5.6
    - 5.5

notifications:
    email: dev@anime-db.org

matrix:
    fast_finish: true
    include:
        - php: 5.6
          env: COVERAGE=1

before_install:
    - if [ "$TRAVIS_PHP_VERSION" == "5.5" ] || [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then echo "extension=memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - if [ "$COVERAGE" != "1" ]; then phpenv config-rm xdebug.ini; fi;
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer self-update
    - mkdir build

install:
    - composer install --prefer-dist --no-interaction --no-progress

script:
    - if [ "$COVERAGE" != "1" ]; then vendor/bin/phpunit; fi;
    - if [ "$COVERAGE" == "1" ]; then vendor/bin/phpunit --coverage-clover build/coverage-clover.xml; fi;

after_script:
    - if [ "$COVERAGE" == "1" ]; then vendor/bin/ocular code-coverage:upload --format=php-clover build/coverage-clover.xml; fi;
    - if [ "$COVERAGE" == "1" ]; then vendor/bin/coveralls -v -c .coveralls.yml; fi;
