parameters:
    cache_time_keeper.track.individually_entity: false
    cache_time_keeper.driver.shmop.salt: '%secret%'
    cache_time_keeper.driver.file.path: '%kernel.root_dir%/cache/cache-time-keeper/'
