services:
    cache_time_keeper.driver.dummy:
        class: AnimeDb\Bundle\CacheTimeKeeperBundle\Service\Driver\Dummy
        public: false

    cache_time_keeper.driver.file:
        class: AnimeDb\Bundle\CacheTimeKeeperBundle\Service\Driver\File
        arguments: [ %cache_time_keeper.driver.dir% ]
        public: false

    cache_time_keeper.driver.shmop:
        class: AnimeDb\Bundle\CacheTimeKeeperBundle\Service\Driver\Shmop
        arguments: [ %cache_time_keeper.salt% ]
        public: false

    cache_time_keeper.driver.multi:
        class: AnimeDb\Bundle\CacheTimeKeeperBundle\Service\Driver\Multi
        arguments: [ @cache_time_keeper.driver.shmop, @cache_time_keeper.driver.file ]
        public: false

    cache_time_keeper:
        class: AnimeDb\Bundle\CacheTimeKeeperBundle\Service\Keeper
        arguments: [ @cache_time_keeper.driver ]

    cache_time_keeper.listener.entity:
        class: AnimeDb\Bundle\CacheTimeKeeperBundle\Event\Listener\Entity
        arguments: [ @cache_time_keeper ]
        tags:
            - { name: doctrine.event_listener, event: postRemove }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }

    cache_time_keeper.listener.console:
        class: AnimeDb\Bundle\CacheTimeKeeperBundle\Event\Listener\Console
        arguments: [ @cache_time_keeper ]
        tags:
            - { name: kernel.event_listener, event: console.terminate, method: onTerminate }
