imports:
    - { resource: 'services/driver.yml' }
    - { resource: 'services/listener.yml' }

services:
    cache_time_keeper:
        class: AnimeDb\Bundle\CacheTimeKeeperBundle\Service\Keeper
        arguments: [ '@cache_time_keeper.driver' ]
