services:
    cache_time_keeper.driver.dummy:
        class: AnimeDb\Bundle\CacheTimeKeeperBundle\Service\Driver\Dummy
        public: false

    cache_time_keeper.driver.file:
        class: AnimeDb\Bundle\CacheTimeKeeperBundle\Service\Driver\File
        arguments: [ %cache_time_keeper.driver.file% ]
        public: false

    cache_time_keeper:
        class: AnimeDb\Bundle\CacheTimeKeeperBundle\Service\Manager
        arguments: [ @cache_time_keeper.driver ]